# ------ Root and Common Configurations ------
root_path: './Dataset'
train_text: 'Dataset/train.txt'
seed: 3407
backbone: './checkpoint/ViT-B-32.pkl'
preprocess_classes: './Dataset/classes_b.txt'

# ------ Hyperparameters ------
search_hp: True
search_scale: [7, 7, 1]
search_step: [200, 20, 20]
init_beta: 1
init_alpha: 0.8
init_gamma: 0.1
eps: 0.001  # 0.01 for 1/2-shot, 0.001 for others
training_feat_num: 900
training_free_feat_num: 700
w_training_free: [0.3, 0.7]
w_training: [0.2, 0.8]
lr: 0.0001
augment_epoch: 10
train_epoch: 30

# ------ Datasets Configuration ------
datasets:
  - name: 'Food-101'
    dataset_path: './Dataset/TrainSet/Food-101/'
  
  - name: 'Caltech-101'
    dataset_path: './Dataset/TrainSet/Caltech-101/'
  
  - name: 'Animal'
    dataset_path: './Dataset/TrainSet/Animal/'
  
  - name: 'Thu-dog'
    dataset_path: './Dataset/TrainSet/Thu-dog/'
